language: cpp
compiler: gcc

os:
  - linux
  - osx
  
addons:
  apt:
    packages: lcov

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install lcov; fi
  - cd test && sudo chmod u+x setup.sh && ./setup.sh
  - cd "${TRAVIS_BUILD_DIR}"
script: "CI=1 make coverage lintall "
after_success:
  -  bash <(curl -s https://codecov.io/bash) -f test/coverage/covdata/hyped.covdata || echo "Codecov did not collect coverage reports"
rvm:
  - 9.00
